import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import Nav from "./components/Nav/Nav";
import style from "./page.module.css";
import NavMobile from "./components/NavMobile/NavMobile";
import Footer from "./components/Footer/Footer";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
});
const poppis = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fitness World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className={style.body}>
        <nav className={inter.className}>
          <Nav />
          <NavMobile />
        </nav>
        {children}
        <Footer />
      </body>
    </html>
  );
}
